GET http://dev.wirlernenonline.de/wp-json/
Accept: application/json

### Ebene 0, Deutsch, sekundarstufe_1
GET http://localhost/wlo/wp-json/portal/v1/add?collectionId=0519cc60-59c2-4d03-8635-201257e3a29c&discipline=https%3A%2F%2Fw3id.org%2Fopeneduhub%2Fvocabs%2Fdiscipline%2F120&educationalContext=https%3A%2F%2Fw3id.org%2Fopeneduhub%2Fvocabs%2FeducationalContext%2Fsekundarstufe_1&title=Deutsch

### Ebene 1, Deutsch - Themenbaum
GET http://localhost/wlo/wp-json/portal/v1/add?collectionId=be567dec-313d-4386-8092-f36b04c44841&discipline=https%3A%2F%2Fw3id.org%2Fopeneduhub%2Fvocabs%2Fdiscipline%2F120&title=Deutsch%20Themenbaum

### Ebene 0, Physik
GET http://localhost/wlo/wp-json/portal/v1/add?collectionId=079e9901-bce1-4c93-89f2-70eb29f021bc&discipline=https%3A%2F%2Fw3id.org%2Fopeneduhub%2Fvocabs%2Fdiscipline%2F460&title=Physik

### Ebene 0, Mathematik
GET http://localhost/wlo/wp-json/portal/v1/add?collectionId=81ef13e4-ad04-46b7-b772-c35eebeb3cdc&discipline=https%3A%2F%2Fw3id.org%2Fopeneduhub%2Fvocabs%2Fdiscipline%2F380&title=Mathematik


###
GET https://redaktion.openeduhub.net/edu-sharing/rest/node/v1/nodes/-home-/0519cc60-59c2-4d03-8635-201257e3a29c/parents?propertyFilter=-all-&fullPath=false
Accept: application/json

###
GET https://redaktion.openeduhub.net/edu-sharing/rest/collection/v1/collections/-home-/c4a5c235-c5da-453d-a936-6bc967fbc6e0/children/references
Accept: application/json

###
