GET http://dev.wirlernenonline.de/wp-json/
Accept: application/json

###
GET http://dev.wirlernenonline.de/wp-json/portal/v1/add?collection_id=7d0367c2-fbaa-484d-96b2-101ac4605e5e&discipline=https%3A%2F%2Fw3id.org%2Fopeneduhub%2Fvocabs%2Fdiscipline%2F120&edu_context=https%3A%2F%2Fw3id.org%2Fopeneduhub%2Fvocabs%2FeducationalContext%2Fsekundarstufe_1&intended_end_user_role=https%3A%2F%2Fw3id.org%2Fopeneduhub%2Fvocabs%2FintendedEndUserRole%2Fteacher&title=Deutsch%20Sekundarstufe%201%20%28Test%29

###

